stages:
  - test
  - figures
  - report

toy-raft-tests:
  image: python:3.6
  stage: test
  script:
    - cd src/toy-raft-implementation/
    - pip install -r requirements.txt
    - python -m unittest discover

thesis-plots:
  stage: figures
  image: python:3.6
  before_script:
    - pip install -r scripts/requirements.txt
  script:
    - data/plot_all.sh
  artifacts:
    paths:
      - thesis/figures/plots/*.pdf
    expire_in: 1 day

thesis-pdf:
  stage: report
  image: antoinealb/texlive
  script:
    - cd thesis
    - latexmk -pdf thesis.tex
    - makeglossaries thesis
    - pdflatex thesis.tex
  artifacts:
    paths:
      - thesis/thesis.pdf
    expire_in: 30 days
