stages:
  - test
  - figures
  - report

toy-raft-tests:
  image: python:3.6
  stage: test
  script:
    - cd src/toy-raft-implementation/
    - pip install -r requirements.txt
    - python -m unittest discover

thesis-pdf:
  stage: report
  image: antoinealb/texlive
  script:
    - cd thesis
    - latexmk -pdf thesis.tex
  artifacts:
    paths:
      - thesis/thesis.pdf
    expire_in: 30 days
